name: ideatree_skilltest
description: ideatree skilltest

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.1
  cupertino_icons: ^0.1.3
  equatable: ^1.2.3
  firebase_messaging: ^6.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.1
  flutter_login_facebook: ^0.2.1
  flutter_screenutil: ^2.3.1
  flutter_polyline_points: ^0.2.2
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.29
  local_auth: ^0.6.2+3
  location: ^3.0.2

dev_dependencies:
  effective_dart: ^1.2.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/